### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingStartTls

### ISSUE THREAD

**Issue by awol2005ex** [stalwartlabs/mail-send#10]
version:  mail-send = "0.3.0"

when not connect to stmp with tls:
`match SmtpClientBuilder::new(email_host,25)
                                    .implicit_tls(false)
                                    .credentials((email_username, email_password))
                                    .timeout(Duration::from_secs(3))
                                    .connect()
                                    .await
                                    .unwrap()
                                    .send(message)
                                    .await
                                {
                                    Ok(_) => println!("Email sent successfully!"),
                                    Err(e) => panic!("Could not send email: {:?}", e),
                                }`

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingStartTls',

**Comment by epompeii** [comment]
I am also having issues with the new version and `implicit_tls()` with the following error `Failed to create TLS connection for email: TLS error: received corrupt message`.

I am trying to connect to [AWS SES on port 587](https://docs.aws.amazon.com/ses/latest/dg/smtp-connect.html).

**Comment by mdecimus** [comment]
> 
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingStartTls',
> 

@awol2005ex This error is because the server does not seem to support the STARTTLS command and you are using the TLS client builder. If you connect manually using telnet and write 

EHLO mydomain.org

do you see STARTTLS listed as a capability? If you don't then you need to use the plain text client builder.

**Comment by mdecimus** [comment]
> I am also having issues with the new version and `implicit_tls()` with the following error `Failed to create TLS connection for email: TLS error: received corrupt message`.
> 
> 
> 
> I am trying to connect to [AWS SES on port 587](https://docs.aws.amazon.com/ses/latest/dg/smtp-connect.html).
> 
> 

Are you setting implicit tls to false?

**Comment by awol2005ex** [comment]
I change the code to
`match SmtpClientBuilder::new(email_host,25)
                                    .implicit_tls(false)
                                    .credentials((email_username, email_password))
                                    .timeout(Duration::from_secs(3))
                                    .connect_plain()
                                    .await
                                    .unwrap()
                                    .send(message)
                                    .await
                                {
                                    Ok(_) => println!("Email sent successfully!"),
                                    Err(e) => panic!("Could not send email: {:?}", e),
                                }`

But error ：
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedReply(Response { code: 220, esc: [0, 0, 0], message: "<domainname> Microsoft ESMTP MAIL Service ready at Wed, 1 Feb 2023 09:22:55 +0800" })', src/main.rs:354:38

The stmp server connect return code is 220 not 200  so go to Err . but 220 is corrent code

**Comment by mdecimus** [comment]
> thread 'main' panicked at 'called Result::unwrap() on an Err value: UnexpectedReply(Response { code: 220, esc: [0, 0, 0], message: " Microsoft ESMTP MAIL Service ready at Wed, 1 Feb 2023 09:22:55 +0800" })', src/main.rs:354:38

There was a bug in the plain text connect which has now been fixed on version 0.3.1.

**Comment by awol2005ex** [comment]
It's OK after upgrade to version 0.3.1

**Comment by awol2005ex** [comment]
It's OK after upgrade to version 0.3.1
