### ISSUE TITLE
MailSend violates the license of its dependency smtp-proto

### ISSUE THREAD

**Issue by SvetlinZarev** [stalwartlabs/mail-send#26]
Mail-send is licensed under mit/apache, while it's dependency smtp-proto - under AGPL3.0. 

AGPL requires all derived work to be licensed under AGPL. Thus mail_send must be AGPL3.0 too. 

Violation of the license of its dependency, makes the mail_send crate unusable.

**Comment by jdevries3133** [comment]
For anyone seeing this, I migrated to [lettre](https://crates.io/crates/lettre), which does not use `smtp-proto` under the hood, and has an MIT license.

**Comment by mdecimus** [comment]
@SvetlinZarev thank you for pointing this out. `smtp-proto` has now been changed to a `MIT/Apache` license, make sure your project is linking version [0.1.3](https://crates.io/crates/smtp-proto).

@jdevries3133 I hope that after this license change you can migrate back to `mail-send`!
