### ISSUE TITLE
impl IntoMessage for Message

### ISSUE THREAD

**Issue by soywod** [stalwartlabs/mail-send#28]
I need the exact conversion method as defined here: https://github.com/stalwartlabs/mail-send/blob/d97850d0c93fc9502097c2073f361458b54f5cf5/src/smtp/message.rs#L283-L285 but from a `mail_parser::Message`. Would you accept a PR based on the same logic, behind a `mail-parser` cargo feature?

**Comment by mdecimus** [comment]
Sure!

**Comment by soywod** [comment]
Could you release a new minor version, if possible?

**Comment by mdecimus** [comment]
Done
